# MainPage Elements
naver_search_field = '//div[@class="search_group"]'
account_container = '//div[@id="account"]'
login_info_text = '//div[@id="account"]/div/p'
login_button = '//div[@id="account"]/div/a'
login_find_id = '//a[contains(text(), "아이디 찾기")]'
login_find_password = '//a[contains(text(), "비밀번호 찾기")]'
login_register = '//a[contains(text(), "회원가입")]'
service_icon_type_cafe = '//span[@class="service_icon type_cafe"]'
service_icon_type_blog = '//span[@class="service_icon type_blog"]'
service_icon_type_shopping = '//span[@class="service_icon type_shopping"]'
service_icon_type_news = '//span[@class="service_icon type_news"]'
service_icon_type_stock = '//span[@class="service_icon type_stock"]'
service_icon_type_real = '//span[@class="service_icon type_real"]'
service_icon_type_map = '//span[@class="service_icon type_map"]'
service_icon_type_webtoon = '//span[@class="service_icon type_webtoon"]'
cafe_main_logo = '//h1[@class="logo"]'
cafe_title = '네이버 카페'
blog_main_logo = '//h1[@class="logo_naver_blog"]'
blog_title = '네이버 블로그'
shopping_main_logo = '//h1[@class="_gnbLogo_title_1xWf-"]'
shopping_title = '네이버쇼핑'
news_main_logo = '//div[@class="Ngnb_left"]'
news_title = '네이버 뉴스'
stock_main_logo = '//div[@class="logo_area"]'
stock_title = '네이버페이 증권'
real_main_logo = '//div[@class="logo_area NE=a:STA"]'
real_title = '네이버페이 부동산'
map_main_logo = '//h1[@class="logo_box"]'
map_title = '네이버 지도'
webtoon_main_logo = '//h1[@class="BrandBar__logo_area--Y_7dM"]'
webtoon_title = '네이버 웹툰'
weather_link_text = '//a[@href="https://weather.naver.com/" and text()="날씨"]'

# LoginPage Elements
login_page_logo = '//a[@class="logo"]'
id_input_field = '//input[@id="id"]'
password_input_field = '//input[@id="pw"]'
login_page_button = '//button[@id="log.login"]'
error_message = '//div[@class="error_message"]'

# WeatherPage Elements
weather_title = '네이버 날씨'
weather_logo = '//h1[@class="logo_area"]'
weather_home_tap = '//a[contains(@href, "/today/") and contains(text(), "홈")]'
weather_compare_tap = '//a[contains(@href, "/compare/") and contains(text(), "예보비교")]'
weather_air_tap = '//a[contains(@href, "/air/") and text() = "미세먼지"]'
weather_map_tap = '//a[contains(@href, "/map/") and contains(text(), "지도")]'

